### PR TITLE
Modernize Python 2 cod to prepare for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
Minor modifications to be syntax compatible with both Python 2 and 3.
* print() is a function in Python 3
* Old style exceptions --> new style for Python 3
* Ran isort on the imports and removed unused imports
* Remove shebang hardcoding of the path to Python

### CODE REVIEW

**Comment by phage-nz** [comment]
Tested your fork in a fresh build. No issues found after a full run.

Thanks very much for helping!

**Comment by cclauss** [comment]
Cool.  You might try __python3 run.py__ and see if that works.

**Comment by phage-nz** [comment]
There are a few things that need to be done before full python3 compatibility - but I'll work on that as I get time to. Relative imports need to be made absolute and a few dependencies will need updating or replacement.

**Comment by cclauss** [comment]
500 daze left... http://pythonclock.org

**Pull request merged**
